= Ren Ying - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: REstaurant Manager

---

== Overview
This portfolio serves the purpose of documenting my contributions to REstaurant Manager (REM),
an application developed by 4 undergraduate students, in the course of Software Engineering Module, CS2103T, in NUS. REstaurant Manager (REM) is a desktop application tailored to restaurant owners of small/medium size restaurants.
This application provides a single platform for them to manage many areas of the restaurant:
customers with membership, staff, bookings, ingredient and recipe inventory.

My role was to implement the ingredient and recipe management features. Other than that, I was in charge of
documentations in the team, to ensure that the features were well documented and corresponded to the actual implementation of the application.
I was also in charge of the Storage component of REM, requiring a thorough concept of the component.

== Summary of Contributions

* *Major enhancement*: added *ingredient and recipe features*
** What it does: allows the user to add, delete, restock and consume ingredients, keeping track of the quantity of ingredients present in the inventory.
Ingredients with quantity in inventory falling below ingredient warning amount can also be listed.
Users can also add and delete recipes consisting of ingredients already present in the inventory, and their respective ingredient quantity per serving for the recipe.
** Justification:
These features improve the product significantly, as the ingredient feature helps to keep track of the inventory status for the ingredients.
The users can choose to restock ingredients if it falls below the user-specified warning amount.
Also, this helps in the user's menu management, as he can ensure sufficient ingredients for the dishes and estimate
number of servings possible with current ingredient inventory. He can then ensure sufficient resources for the smooth running
of the restaurant, according to the estimation of busyness of the restaurant via booking and statistics features.
** Highlights: It was challenging to implement recipe feature, as recipe is highly tied to ingredients, and change
in any of the ingredient quantities of a recipe should cause a change in the recipe and number of servings possible.
Since recipes can contain more than 1 ingredient, this also increases the complexity of the data structure required to store the ingredients.

* *Code contributed*: [https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#search=hiyingnn&sort=displayName&since=2019-02-10&until=2019-04-08&timeframe=day&reverse=false&repoSort=true[Code]]

* *Other contributions*:
** Project management:
*** Wrote tests to increase coverage (Pull requests https://github.com/cs2103-ay1819S2-w11-2/main/pull/28[#28])
*** Implemented storage component for ingredient (Pull requests https://github.com/cs2103-ay1819S2-w11-2/main/pull/35[#35])
*** Refactored project (Pull requests https://github.com/cs2103-ay1819S2-w11-2/main/pull/28[#28])

** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide/ Developer Guide: (Pull requests https://github.com/cs2103-ay1819S2-w11-2/main/pull/202[#202])

** Community:
*** PRs reviewed (with non-trivial review comments):  (Pull requests https://github.com/cs2103-ay1819S2-w11-2/main/pull/106[#106])
*** Reported bugs for other teams: (Pull requests https://github.com/CS2103-AY1819S2-W17-2/main/issues/164[#164])


== Contributions to the User Guide
|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=inventory]


== Contributions to the Developer Guide
|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=delete]

